on: pull_request

jobs:
  example_comment_pr:
    runs-on: ubuntu-latest
    permissions: write-all
    name: An example job to comment a PR
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v3
        with:
          message: |
             Please do a Self Review! Make sure everything is correct. Thank you ! :wave:
